In [0]:
import torch

## A Single Neuron

![](https://user-images.githubusercontent.com/1741387/60381443-3b6c7b00-9a7f-11e9-9bbb-41030b6b2c97.png)

In [2]:
seed = 42

# If you want to random the seed number
# https://pytorch.org/docs/master/torch.html#torch.randint
# torch.randint(<highest integer>,  <a tuple defining the shape of the output tensor>)
# .item() gets the value inside the tensor
# Random from 0 - 100 with Tensor output size (1,1)
# seed = torch.randint(100, (1,1)).item()

# https://pytorch.org/docs/stable/torch.html?highlight=manual_seed#torch.manual_seed
torch.manual_seed(seed)

# Define 5 features, 5 weights, and 1 bias
# https://pytorch.org/docs/master/torch.html#torch.randn
features = torch.randn((1, 5))
print('Features: \n{}\n'.format(features))

# Creates another tensor with the same shape as features
# https://pytorch.org/docs/stable/torch.html#torch.randn_like
weights = torch.randn_like(features)
print('Weights: \n{}\n'.format(weights))

bias = torch.randn((1, 1))
print('Bias: \n{}'.format(bias))

Features: 
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229]])

Weights: 
tensor([[-0.1863,  2.2082, -0.6380,  0.4617,  0.2674]])

Bias: 
tensor([[0.5349]])


## Activation Function

![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Logistic-curve.svg/600px-Logistic-curve.svg.png)

In [0]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

## Calculate the output of this network using the weights and bias tensors

In [5]:
y = activation(torch.sum(features * weights) + bias)
print(y)

tensor([[0.6018]])


In [6]:
y = activation((features * weights).sum() + bias)
print(y)

tensor([[0.6018]])


In [7]:
print(weights)
print(weights.shape)

tensor([[-0.1863,  2.2082, -0.6380,  0.4617,  0.2674]])
torch.Size([1, 5])


In [11]:
# Error
#y = torch.mm(features, weights)
print(weights.view(5,1))
print(weights.view(5,1).shape)
print(weights.t())

tensor([[-0.1863],
        [ 2.2082],
        [-0.6380],
        [ 0.4617],
        [ 0.2674]])
torch.Size([5, 1])
tensor([[-0.1863],
        [ 2.2082],
        [-0.6380],
        [ 0.4617],
        [ 0.2674]])


In [10]:
y = activation(torch.mm(features, weights.view(5,1)) + bias)
print(y)

tensor([[0.6018]])


## A Simple Neural Network

![](https://raw.githubusercontent.com/udacity/deep-learning-v2-pytorch/master/intro-to-pytorch/assets/multilayer_diagram_weights.png)

In [12]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))
print(features)

tensor([[-0.1468,  0.7861,  0.9468]])


In [0]:
# Define the size of each layer in our network

# Number of input units, must match number of input features
n_input = features.shape[1]     

# Number of hidden units 
n_hidden = 2      

# Number of output units
n_output = 1                    

In [15]:
# Weights for inputs to hidden layer, (3, 2)
W1 = torch.randn(n_input, n_hidden)
print(W1)

tensor([[-1.6822,  0.3177],
        [ 0.1328,  0.1373],
        [ 0.2405,  1.3955]])


In [16]:
# Weights for hidden layer to output layer, (2, 1)
W2 = torch.randn(n_hidden, n_output)
print(W2)

tensor([[1.3470],
        [2.4382]])


In [17]:
# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

print(B1)
print(B2)

tensor([[0.2028, 2.4505]])
tensor([[2.0256]])


## Calculate the output result

In [18]:
h = activation(torch.mm(features, W1) + B1)
print(h)

tensor([[0.6861, 0.9788]])


In [0]:
output = activation(torch.mm(h, W2) + B2)

In [20]:
print(output)

tensor([[0.9952]])
